import Head from 'next/head'
import Footer from '../components/Footer/Footer'
import Gretting from '../components/Grettings/Gretting'
import Navbar from '../components/Navbar/Navbar'
import Skills from '../components/Skills/Skills'



export default function Home() {
  return (
    <div >
      <Head>
        <title>HK | Full stack developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/my.ico" />
      </Head>
      <Navbar/>
      <Gretting/>
      <Skills/>
    
      <Footer/>
    </div>
  )
}
