import Head from 'next/head'
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import AboutMe from './AboutMe'






export default function Home() {
  const { t } = useTranslation();
  
  return (
    <div >
      <Head>
        <title>HK | Full stack developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/my.ico" />
      </Head>
      <AboutMe/>
    </div>
  )
}


export async function getStaticProps({ locale }) {
    return {
      props: {
        ...(await serverSideTranslations(locale, ["common"])),
      },
    };
  }