import Head from 'next/head'
import Navbar from './components/Navbar/Navbar'



export default function Home() {
  return (
    <div >
      <Head>
        <title>HK | Full stack developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/my.ico" />
      </Head>
      <Navbar/>
    </div>
  )
}
